-- ============================================================
-- Axionia — migration 041: fix promote_research_to_report's signature
--
-- Production is running a function this repo does not define:
--
--     promote_research_to_report(p_run_id uuid, p_user_id uuid, p_title text)
--
-- while every caller passes (run_id, domain, title). research_schema.sql
-- creates the correct one inside conditional DO blocks that skip silently
-- and only `raise notice` when report_requests / origin / reports.user_id
-- aren't in the expected state — so on the run that mattered it was skipped,
-- and the axionia-app-era version was left in place.
--
-- The consequence was not a visible error. The old function promotes
-- happily; it just never anchors the report to a company, so company_id
-- came back null on all nineteen reports produced since. Every
-- company-scoped query on the site — "prior reports for this company", the
-- company hub, the RLS path a client reads through — was therefore blind to
-- reports that existed, had content, and were correct.
--
-- The old overload is DROPPED rather than left beside the new one. Both
-- present, a call of promote_research_to_report(uuid, null, null) is
-- ambiguous between (uuid, uuid, text) and (uuid, text, text), and Postgres
-- refuses it outright — turning a silent wrong answer into a hard failure
-- for every run.
--
-- Run AFTER 040. Safe to re-run.
-- ============================================================

drop function if exists research.promote_research_to_report(uuid, uuid, text);

  create or replace function research.promote_research_to_report(
    p_run_id uuid,
    p_domain text default null,   -- overrides the domain derived from website
    p_title  text default null
  )
  returns uuid
  language plpgsql
  security definer set search_path = research, public
  as $body$
  declare
    v_report_id  uuid;
    v_request_id uuid;
    v_company_id uuid;
    v_name       text;
    v_website    text;
    v_payload    jsonb;
    v_summary    text;
    v_domain        text;
    v_stored_domain text;
    v_prior_id   uuid;
    v_version    int := 1;
    v_kind       public.request_kind := 'new';
  begin
    select c.name, c.website, c.domain, r.full_payload,
           r.scores ->> 'topOpportunity'
      into v_name, v_website, v_stored_domain, v_payload, v_summary
      from research.research_runs r
      join research.companies c on c.id = r.company_id
     where r.id = p_run_id;

    if v_name is null then
      raise exception 'research run % not found', p_run_id;
    end if;

    -- Explicit arg wins, then whatever the save path already resolved, then
    -- the website, then a placeholder. Same functions the save path uses.
    v_domain := coalesce(
      research.normalize_domain(p_domain),
      v_stored_domain,
      research.normalize_domain(v_website),
      research.placeholder_domain(v_name)
    );

    -- Aliased "pc": schema-qualified column refs are not valid in DO UPDATE.
    -- Existing name wins — the site may have a hand-corrected value.
    insert into public.companies as pc (domain, name)
    values (v_domain, v_name)
    on conflict (domain) do update
      set name = coalesce(pc.name, excluded.name)
    returning id into v_company_id;

    -- Version chain: a second run on the same company is a refresh.
    select id, version into v_prior_id, v_version
      from public.reports
     where company_id = v_company_id
     order by version desc
     limit 1;

    if v_prior_id is null then
      v_version := 1;
      v_kind    := 'new';
    else
      v_version := v_version + 1;
      v_kind    := 'refresh';
    end if;

    -- Queue row, so this appears in the admin UI alongside inbound work.
    -- No contact_email / user_id: 007 made both nullable for exactly this.
    insert into public.report_requests
      (user_id, company_id, contact_email, company_name, kind, status, origin, payload, admin_notes)
    values
      (null, v_company_id, null, v_name, v_kind, 'in_review', 'admin',
       jsonb_build_object('research_run_id', p_run_id, 'source', 'axionia-app pipeline'),
       'Generated by the Axionia Research Agent. Requires review before release.')
    returning id into v_request_id;

    insert into public.reports
      (user_id, company_id, request_id, title, status, content, summary, version, supersedes_id)
    values
      (null, v_company_id, v_request_id,
       coalesce(p_title, v_name || ' — Benefit Intelligence Report'),
       'in_review', v_payload, v_summary, v_version, v_prior_id)
    returning id into v_report_id;

    return v_report_id;
  end;
  $body$;

-- ────────────────────────────────────────────────────────────
-- VERIFY
-- ────────────────────────────────────────────────────────────
select 'exactly one promote function' as check,
       count(*) = 1 as ok
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
 where n.nspname = 'research'
   and p.proname = 'promote_research_to_report'
union all
select 'second arg is p_domain text',
       pg_get_function_identity_arguments(p.oid) = 'p_run_id uuid, p_domain text, p_title text'
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
 where n.nspname = 'research'
   and p.proname = 'promote_research_to_report';
